# Generated by Django 5.0.6 on 2024-05-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=45)),
                ('category', models.IntegerField()),
                ('size', models.IntegerField()),
                ('color', models.IntegerField()),
                ('material', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=45)),
            ],
        ),
    ]
