# Generated by Django 5.0.6 on 2024-05-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='product'),
        ),
    ]
